[env:adafruit_feather_m0]
platform  = atmelsam
board     = adafruit_feather_m0
framework = arduino

monitor_speed = 115200
monitor_port  = COM8

lib_deps =
    adafruit/Adafruit BMP5xx Library @ ^1.0
    adafruit/Adafruit Unified Sensor  @ ^1.1
    arduino-libraries/WiFi101         @ ^0.16
    arduino-libraries/ArduinoMqttClient @ ^0.1
    bblanchon/ArduinoJson             @ ^6.21
